/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**
**     @file      lin_cfg.h
**
**     @date      14:57:55, 2021-12-26
**
**     @brief     Hardware configuration file
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016 - 2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/

/*!
 * @file lin_cfg.h
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.3, A project should not contain unused type declarations.
 * The type can be used by user application.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, A project should not contain unused macro declarations.
 * The macro can be used by user application.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.1, External identifiers shall be distinct.
 * The identifiers are generated from signal names. The signal name is defined by users and we can not control this.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.2, Identifiers declared in the same scope and name
 * space shall be distinct.
 * The name of signal is defined by user and we can not control this.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.4, Macro identifiers shall be distinct.
 * The name of signal is defined by user and we can not control this.
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 5.5, Identifier shall be distinct from macro names.
 * The name of signal is defined by user and we can not control this.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Directive 4.9, A function should be used in preference
 * to a function-like macro where they are interchangeable.
 * The macro is used to define static or dynamic implementation of API functions.
 * This way is more efficient.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 20.10, The #/ ## preprocessor operator should not be used.
 * The operator is used to define dynamic implementation of API functions of signal interaction.
 * This way is more efficient.
 */
#ifndef    LIN_CFG_H
#define    LIN_CFG_H

#include <stdint.h>
#include "lin_driver.h"
#include "lin1.h"

/* Implements    : SUPPORT_MASTER_MODE_Class */
#define SUPPORT_MASTER_MODE     0U /* Equal to 1 when have at least one master interface */
/* Implements    : SUPPORT_SLAVE_MODE_Class */
#define SUPPORT_SLAVE_MODE      1U  /* Equal to 1 when have at least one slave interface */

/* Implements    : SUPPORT_PROTOCOL_21_Class */
#define SUPPORT_PROTOCOL_21     1U /* Equal to 1 when have at least one LIN2.1 or LIN2.2 interface */
/* Implements    : SUPPORT_PROTOCOL_J2602_Class */
#define SUPPORT_PROTOCOL_J2602  0U /* Equal to 1 when have at least one J2602 interface */

/* Implements    : SUPPORT_DIAG_CLASS_III_Class */
#define SUPPORT_DIAG_CLASS_III  1U /* Equal to 1 when have at least one ifc with diagnostic class III */
/* Implements    : SUPPORT_DIAG_CLASS_II_Class */
#define SUPPORT_DIAG_CLASS_II   1U /* Equal to 1 when have at least one ifc with diagnostic class II or III */

/* Implements    : SUPPORT_TRANSPORT_LAYER_Class */
#define SUPPORT_TRANSPORT_LAYER 1U /* Equal to 1 to use transport layer */
/* Implements    : SUPPORT_DIAG_SERVICE_Class */
#define SUPPORT_DIAG_SERVICE    1U /* Equal to 1 to use diagnostic service layer */
#define TIME_OUT_UNIT_US 1000U

#define HARDWARE_INSTANCE_COUNT    2U

#define LIN_NUM_OF_IFCS  1U
#define LIN_NUM_OF_SLAVE_IFCS 1U
#define LIN_NUM_OF_MASTER_IFCS 0U

/* frame buffer size */
#define LIN_FRAME_BUF_SIZE          32U
#define LIN_FLAG_BUF_SIZE           8U

/**********************************************************************/
/***************               Interfaces           *******************/
/**********************************************************************/
typedef enum {
   LI0 = 0x00U,
   INVALID_IFC = 0xFFU
}l_ifc_handle;

typedef enum {
   LI0_Slave = 0x00U,
   INVALID_SLAVE_INDEX = 0xFFU
}l_ifc_slave_handle;
typedef enum {
   INVALID_MASTER_INDEX = 0xFFU
}l_ifc_master_handle;

/**********************************************************************/
/***************               Signals              *******************/
/**********************************************************************/
/* Number of signals */
#define LIN_NUM_OF_SIGS  30U
/* List of signals */
typedef enum {

   /* Interface_name = LI0 */

   LI0_MFS_RPressSignal1

   , LI0_MFS_RPressSignal2
  
   , LI0_MFS_RPressSignal3
  
   , LI0_MFS_UP_switch_signal
  
   , LI0_MFS_DOWN_switch_signal
  
   , LI0_MFS_LEFT_switch_signal
  
   , LI0_MFS_RIGHT_switch_signal
  
   , LI0_MFS_OK_switch_signal
  
   , LI0_MFS_LPressSignal1
  
   , LI0_MFS_LPressSignal2
  
   , LI0_MFS_LPressSignal3
  
   , LI0_MFS_LIN_1_Error
  
   , LI0_L_BYTE1
  
   , LI0_L_BYTE2
  
   , LI0_L_BYTE3
  
   , LI0_L_BYTE4
  
   , LI0_L_BYTE5
  
   , LI0_L_BYTE6
  
   , LI0_L_BYTE7
  
   , LI0_L_BYTE8
  
   , LI0_GW_Backlight
  
   , LI0_GW_BYTE1
  
   , LI0_GW_BYTE2
  
   , LI0_GW_BYTE3
  
   , LI0_GW_BYTE4
  
   , LI0_GW_BYTE5
  
   , LI0_GW_BYTE6
  
   , LI0_L_Rolling
  
   , LI0_L_Checksum
  
   , LI0_L_LB
  
} l_signal_handle;
/**********************************************************************/
/*****************               Frame             ********************/
/**********************************************************************/
/* Number of frames */
#define LIN_NUM_OF_FRMS  6U
/* List of frames */
typedef enum {
/* All frames for master node */

   /* Interface_name = LI0 */

   LI0_MFS_LIN_1

   , LI0_TestFrame1
  
   , LI0_MFS_LIN_2
  
   , LI0_GW_LIN
  
   , LI0_MasterReq
  
   , LI0_SlaveResp
  
} l_frame_handle;
/**********************************************************************/
/***************             Configuration          *******************/
/**********************************************************************/


/* Size of configuration in ROM and RAM used for interface: LI0 */
#define LI0_LIN_SIZE_OF_CFG  10U



/*********************************************************************
 * global macros
 *********************************************************************/
/*FUNCTION**********************************************************************
 *
 * Function Name : l_bool_rd
 * Description   : This function return value of bool signal
 *
 * Implements    : l_bool_rd_Class
 *END**************************************************************************/
#define l_bool_rd(SIGNAL) l_bool_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bool_wr
 * Description   : This function write value A to bool signal
 *
 * Implements    : l_bool_wr_Class
 *END**************************************************************************/
#define l_bool_wr(SIGNAL, A) l_bool_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_u8_rd
 * Description   : This function read data from (1-8 bit)signal
 *
 * Implements    : l_u8_rd_Class
 *END**************************************************************************/
#define l_u8_rd(SIGNAL) l_u8_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : l_u8_wr
 * Description   : This this function write data to (1-8 bit)signal
 *
 * Implements    : l_u8_wr_Class
 *END**************************************************************************/
#define l_u8_wr(SIGNAL, A) l_u8_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_u16_rd
 * Description   : This function read data from (8-16 bit)signal
 *
 * Implements    : l_u16_rd_Class
 *END**************************************************************************/
#define l_u16_rd(SIGNAL) l_u16_rd_##SIGNAL()

/*FUNCTION**********************************************************************
 *
 * Function Name : l_u16_wr
 * Description   : This function write data to (8-16 bit) signal
 *
 * Implements    : l_u16_wr_Class
 *END**************************************************************************/
#define l_u16_wr(SIGNAL, A) l_u16_wr_##SIGNAL(A)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bytes_rd
 * Description   : This function read data from bytes signal
 *
 * Implements    : l_bytes_rd_Class
 *END**************************************************************************/
#define l_bytes_rd(SIGNAL, start, count, data)  l_bytes_rd_##SIGNAL(start, count, data)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_bytes_wr
 * Description   : This function write data to bytes signal
 *
 * Implements    : l_bytes_wr_Class
 *END**************************************************************************/
#define l_bytes_wr(SIGNAL, start, count, data) l_bytes_wr_##SIGNAL(start, count, data)

/*FUNCTION**********************************************************************
 *
 * Function Name : l_flg_tst
 * Description   : This function return value of flag which related with signal
 *
 * Implements    : l_flg_tst_Class
 *END**************************************************************************/
#define l_flg_tst(FLAG) l_flg_tst_##FLAG()

/*FUNCTION**********************************************************************
 *
 * Function Name : l_flg_clr
 * Description   : This function clear flag which related with signal
 *
 * Implements    : l_flg_clr_Class
 *END**************************************************************************/
#define l_flg_clr(FLAG) l_flg_clr_##FLAG()

#define LIN_TEST_BIT(A,B) ((l_bool)((((A) & (1U << (B))) != 0U) ? 1U : 0U))
#define LIN_SET_BIT(A,B)                      ((A) |= (l_u8) (1U << (B)))
#define LIN_CLEAR_BIT(A,B)               ((A) &= ((l_u8) (~(1U << (B)))))
#define LIN_BYTE_MASK  ((l_u16)(((l_u16)((l_u16)1 << CHAR_BIT)) - (l_u16)1))


/* Returns the low byte of the 32-bit value    */
#define BYTE_0(n)                              ((l_u8)((n) & (l_u8)0xFF))
/* Returns the second byte of the 32-bit value */
#define BYTE_1(n)                        ((l_u8)(BYTE_0((n) >> (l_u8)8)))
/* Returns the third byte of the 32-bit value  */
#define BYTE_2(n)                       ((l_u8)(BYTE_0((n) >> (l_u8)16)))
/* Returns high byte of the 32-bit value       */
#define BYTE_3(n)                       ((l_u8)(BYTE_0((n) >> (l_u8)24)))

/*
 * defines for signal access
 */



#define LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET    18U
#define LIN_LI0_MFS_RPressSignal1_BIT_OFFSET    0U
#define LIN_LI0_MFS_RPressSignal1_SIGNAL_SIZE    12U
#define LIN_LI0_MFS_RPressSignal1_FLAG_BYTE_OFFSET    3U
#define LIN_LI0_MFS_RPressSignal1_FLAG_BIT_OFFSET    7U


#define LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET    19U
#define LIN_LI0_MFS_RPressSignal2_BIT_OFFSET    4U
#define LIN_LI0_MFS_RPressSignal2_SIGNAL_SIZE    12U
#define LIN_LI0_MFS_RPressSignal2_FLAG_BYTE_OFFSET    4U
#define LIN_LI0_MFS_RPressSignal2_FLAG_BIT_OFFSET    0U


#define LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET    21U
#define LIN_LI0_MFS_RPressSignal3_BIT_OFFSET    0U
#define LIN_LI0_MFS_RPressSignal3_SIGNAL_SIZE    12U
#define LIN_LI0_MFS_RPressSignal3_FLAG_BYTE_OFFSET    4U
#define LIN_LI0_MFS_RPressSignal3_FLAG_BIT_OFFSET    1U


#define LIN_LI0_MFS_UP_switch_signal_BYTE_OFFSET    0U
#define LIN_LI0_MFS_UP_switch_signal_BIT_OFFSET    0U
#define LIN_LI0_MFS_UP_switch_signal_SIGNAL_SIZE    2U
#define LIN_LI0_MFS_UP_switch_signal_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_UP_switch_signal_FLAG_BIT_OFFSET    0U


#define LIN_LI0_MFS_DOWN_switch_signal_BYTE_OFFSET    0U
#define LIN_LI0_MFS_DOWN_switch_signal_BIT_OFFSET    2U
#define LIN_LI0_MFS_DOWN_switch_signal_SIGNAL_SIZE    2U
#define LIN_LI0_MFS_DOWN_switch_signal_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_DOWN_switch_signal_FLAG_BIT_OFFSET    1U


#define LIN_LI0_MFS_LEFT_switch_signal_BYTE_OFFSET    0U
#define LIN_LI0_MFS_LEFT_switch_signal_BIT_OFFSET    4U
#define LIN_LI0_MFS_LEFT_switch_signal_SIGNAL_SIZE    2U
#define LIN_LI0_MFS_LEFT_switch_signal_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_LEFT_switch_signal_FLAG_BIT_OFFSET    2U


#define LIN_LI0_MFS_RIGHT_switch_signal_BYTE_OFFSET    0U
#define LIN_LI0_MFS_RIGHT_switch_signal_BIT_OFFSET    6U
#define LIN_LI0_MFS_RIGHT_switch_signal_SIGNAL_SIZE    2U
#define LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BIT_OFFSET    3U


#define LIN_LI0_MFS_OK_switch_signal_BYTE_OFFSET    1U
#define LIN_LI0_MFS_OK_switch_signal_BIT_OFFSET    0U
#define LIN_LI0_MFS_OK_switch_signal_SIGNAL_SIZE    2U
#define LIN_LI0_MFS_OK_switch_signal_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_OK_switch_signal_FLAG_BIT_OFFSET    4U


#define LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET    2U
#define LIN_LI0_MFS_LPressSignal1_BIT_OFFSET    0U
#define LIN_LI0_MFS_LPressSignal1_SIGNAL_SIZE    12U
#define LIN_LI0_MFS_LPressSignal1_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_LPressSignal1_FLAG_BIT_OFFSET    7U


#define LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET    3U
#define LIN_LI0_MFS_LPressSignal2_BIT_OFFSET    4U
#define LIN_LI0_MFS_LPressSignal2_SIGNAL_SIZE    12U
#define LIN_LI0_MFS_LPressSignal2_FLAG_BYTE_OFFSET    1U
#define LIN_LI0_MFS_LPressSignal2_FLAG_BIT_OFFSET    0U


#define LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET    5U
#define LIN_LI0_MFS_LPressSignal3_BIT_OFFSET    0U
#define LIN_LI0_MFS_LPressSignal3_SIGNAL_SIZE    12U
#define LIN_LI0_MFS_LPressSignal3_FLAG_BYTE_OFFSET    1U
#define LIN_LI0_MFS_LPressSignal3_FLAG_BIT_OFFSET    1U


#define LIN_LI0_MFS_LIN_1_Error_BYTE_OFFSET    1U
#define LIN_LI0_MFS_LIN_1_Error_BIT_OFFSET    7U
#define LIN_LI0_MFS_LIN_1_Error_SIGNAL_SIZE    1U
#define LIN_LI0_MFS_LIN_1_Error_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_MFS_LIN_1_Error_FLAG_BIT_OFFSET    6U


#define LIN_LI0_L_BYTE1_BYTE_OFFSET    8U
#define LIN_LI0_L_BYTE1_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE1_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE1_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE1_FLAG_BIT_OFFSET    0U


#define LIN_LI0_L_BYTE2_BYTE_OFFSET    9U
#define LIN_LI0_L_BYTE2_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE2_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE2_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE2_FLAG_BIT_OFFSET    1U


#define LIN_LI0_L_BYTE3_BYTE_OFFSET    10U
#define LIN_LI0_L_BYTE3_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE3_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE3_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE3_FLAG_BIT_OFFSET    2U


#define LIN_LI0_L_BYTE4_BYTE_OFFSET    11U
#define LIN_LI0_L_BYTE4_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE4_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE4_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE4_FLAG_BIT_OFFSET    3U


#define LIN_LI0_L_BYTE5_BYTE_OFFSET    12U
#define LIN_LI0_L_BYTE5_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE5_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE5_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE5_FLAG_BIT_OFFSET    4U


#define LIN_LI0_L_BYTE6_BYTE_OFFSET    13U
#define LIN_LI0_L_BYTE6_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE6_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE6_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE6_FLAG_BIT_OFFSET    5U


#define LIN_LI0_L_BYTE7_BYTE_OFFSET    14U
#define LIN_LI0_L_BYTE7_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE7_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE7_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE7_FLAG_BIT_OFFSET    6U


#define LIN_LI0_L_BYTE8_BYTE_OFFSET    15U
#define LIN_LI0_L_BYTE8_BIT_OFFSET    0U
#define LIN_LI0_L_BYTE8_SIGNAL_SIZE    8U
#define LIN_LI0_L_BYTE8_FLAG_BYTE_OFFSET    2U
#define LIN_LI0_L_BYTE8_FLAG_BIT_OFFSET    7U


#define LIN_LI0_GW_Backlight_BYTE_OFFSET    25U
#define LIN_LI0_GW_Backlight_BIT_OFFSET    0U
#define LIN_LI0_GW_Backlight_SIGNAL_SIZE    8U
#define LIN_LI0_GW_Backlight_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_Backlight_FLAG_BIT_OFFSET    0U


#define LIN_LI0_GW_BYTE1_BYTE_OFFSET    26U
#define LIN_LI0_GW_BYTE1_BIT_OFFSET    0U
#define LIN_LI0_GW_BYTE1_SIGNAL_SIZE    8U
#define LIN_LI0_GW_BYTE1_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_BYTE1_FLAG_BIT_OFFSET    1U


#define LIN_LI0_GW_BYTE2_BYTE_OFFSET    27U
#define LIN_LI0_GW_BYTE2_BIT_OFFSET    0U
#define LIN_LI0_GW_BYTE2_SIGNAL_SIZE    8U
#define LIN_LI0_GW_BYTE2_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_BYTE2_FLAG_BIT_OFFSET    2U


#define LIN_LI0_GW_BYTE3_BYTE_OFFSET    28U
#define LIN_LI0_GW_BYTE3_BIT_OFFSET    0U
#define LIN_LI0_GW_BYTE3_SIGNAL_SIZE    8U
#define LIN_LI0_GW_BYTE3_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_BYTE3_FLAG_BIT_OFFSET    3U


#define LIN_LI0_GW_BYTE4_BYTE_OFFSET    29U
#define LIN_LI0_GW_BYTE4_BIT_OFFSET    0U
#define LIN_LI0_GW_BYTE4_SIGNAL_SIZE    8U
#define LIN_LI0_GW_BYTE4_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_BYTE4_FLAG_BIT_OFFSET    4U


#define LIN_LI0_GW_BYTE5_BYTE_OFFSET    30U
#define LIN_LI0_GW_BYTE5_BIT_OFFSET    0U
#define LIN_LI0_GW_BYTE5_SIGNAL_SIZE    8U
#define LIN_LI0_GW_BYTE5_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_BYTE5_FLAG_BIT_OFFSET    5U


#define LIN_LI0_GW_BYTE6_BYTE_OFFSET    31U
#define LIN_LI0_GW_BYTE6_BIT_OFFSET    0U
#define LIN_LI0_GW_BYTE6_SIGNAL_SIZE    8U
#define LIN_LI0_GW_BYTE6_FLAG_BYTE_OFFSET    5U
#define LIN_LI0_GW_BYTE6_FLAG_BIT_OFFSET    6U


#define LIN_LI0_L_Rolling_BYTE_OFFSET    6U
#define LIN_LI0_L_Rolling_BIT_OFFSET    4U
#define LIN_LI0_L_Rolling_SIGNAL_SIZE    4U
#define LIN_LI0_L_Rolling_FLAG_BYTE_OFFSET    1U
#define LIN_LI0_L_Rolling_FLAG_BIT_OFFSET    2U


#define LIN_LI0_L_Checksum_BYTE_OFFSET    7U
#define LIN_LI0_L_Checksum_BIT_OFFSET    0U
#define LIN_LI0_L_Checksum_SIGNAL_SIZE    8U
#define LIN_LI0_L_Checksum_FLAG_BYTE_OFFSET    1U
#define LIN_LI0_L_Checksum_FLAG_BIT_OFFSET    3U


#define LIN_LI0_L_LB_BYTE_OFFSET    1U
#define LIN_LI0_L_LB_BIT_OFFSET    2U
#define LIN_LI0_L_LB_SIGNAL_SIZE    2U
#define LIN_LI0_L_LB_FLAG_BYTE_OFFSET    0U
#define LIN_LI0_L_LB_FLAG_BIT_OFFSET    5U



/**********************************************************************/
/***************        Static API Functions        *******************/
/**********************************************************************/
/*
 * the static signal access macros
 */


 
/* static access macros for signal LI0_MFS_RPressSignal1 */
 
#define l_u16_rd_LI0_MFS_RPressSignal1() \
    ((l_u16)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET] + (g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xfffU))


#define l_u16_wr_LI0_MFS_RPressSignal1(A) \
    { \
    g_buffer_backup_data[2U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] |= (1U << 2); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    g_buffer_backup_data[2U + 1U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET + 1U]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] |= (1U << (2 + 1U)); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET + 1U] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal1_BYTE_OFFSET + 1U] & 0xf0U) | \
    (((A) >> 8U) & 0x0fU)); \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] &= (~(0x03 << 2)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal1_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal1_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_RPressSignal2 */
 
#define l_u16_rd_LI0_MFS_RPressSignal2() \
    ((l_u16)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET] + (g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET + 1U] << 8U)) >> 4U) & 0xfffU))


#define l_u16_wr_LI0_MFS_RPressSignal2(A) \
    { \
    g_buffer_backup_data[3U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] |= (1U << 3); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    g_buffer_backup_data[3U + 1U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET + 1U]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] |= (1U << (3 + 1U)); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET + 1U] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal2_BYTE_OFFSET + 1U] & 0x00U) | \
    (((A) >> 4U) & 0xffU)); \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] &= (~(0x03 << 3)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal2_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal2_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_RPressSignal3 */
 
#define l_u16_rd_LI0_MFS_RPressSignal3() \
    ((l_u16)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET] + (g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xfffU))


#define l_u16_wr_LI0_MFS_RPressSignal3(A) \
    { \
    g_buffer_backup_data[5U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] |= (1U << 5); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    g_buffer_backup_data[5U + 1U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET + 1U]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] |= (1U << (5 + 1U)); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET + 1U] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RPressSignal3_BYTE_OFFSET + 1U] & 0xf0U) | \
    (((A) >> 8U) & 0x0fU)); \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_2] &= (~(0x03 << 5)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal3_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal3_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_UP_switch_signal */
 
#define l_u8_rd_LI0_MFS_UP_switch_signal() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_UP_switch_signal_BYTE_OFFSET]) >> 0U) & 0x03U))


#define l_u8_wr_LI0_MFS_UP_switch_signal(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_MFS_UP_switch_signal_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_UP_switch_signal_BYTE_OFFSET] & 0xfcU) | \
    (((A) << 0U) & 0x03U)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_UP_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_UP_switch_signal_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_DOWN_switch_signal */
 
#define l_u8_rd_LI0_MFS_DOWN_switch_signal() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_DOWN_switch_signal_BYTE_OFFSET]) >> 2U) & 0x03U))


#define l_u8_wr_LI0_MFS_DOWN_switch_signal(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_MFS_DOWN_switch_signal_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_DOWN_switch_signal_BYTE_OFFSET] & 0xf3U) | \
    (((A) << 2U) & 0x0cU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_DOWN_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_DOWN_switch_signal_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_LEFT_switch_signal */
 
#define l_u8_rd_LI0_MFS_LEFT_switch_signal() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_LEFT_switch_signal_BYTE_OFFSET]) >> 4U) & 0x03U))


#define l_u8_wr_LI0_MFS_LEFT_switch_signal(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LEFT_switch_signal_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LEFT_switch_signal_BYTE_OFFSET] & 0xcfU) | \
    (((A) << 4U) & 0x30U)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LEFT_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LEFT_switch_signal_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_RIGHT_switch_signal */
 
#define l_u8_rd_LI0_MFS_RIGHT_switch_signal() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_RIGHT_switch_signal_BYTE_OFFSET]) >> 6U) & 0x03U))


#define l_u8_wr_LI0_MFS_RIGHT_switch_signal(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_MFS_RIGHT_switch_signal_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_RIGHT_switch_signal_BYTE_OFFSET] & 0x3fU) | \
    (((A) << 6U) & 0xc0U)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_OK_switch_signal */
 
#define l_u8_rd_LI0_MFS_OK_switch_signal() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_OK_switch_signal_BYTE_OFFSET]) >> 0U) & 0x03U))


#define l_u8_wr_LI0_MFS_OK_switch_signal(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_MFS_OK_switch_signal_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_OK_switch_signal_BYTE_OFFSET] & 0xfcU) | \
    (((A) << 0U) & 0x03U)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_OK_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_OK_switch_signal_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_LPressSignal1 */
 
#define l_u16_rd_LI0_MFS_LPressSignal1() \
    ((l_u16)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET] + (g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xfffU))


#define l_u16_wr_LI0_MFS_LPressSignal1(A) \
    { \
    g_buffer_backup_data[2U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] |= (1U << 2); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    g_buffer_backup_data[2U + 1U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET + 1U]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] |= (1U << (2 + 1U)); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET + 1U] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal1_BYTE_OFFSET + 1U] & 0xf0U) | \
    (((A) >> 8U) & 0x0fU)); \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] &= (~(0x03 << 2)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal1_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal1_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_LPressSignal2 */
 
#define l_u16_rd_LI0_MFS_LPressSignal2() \
    ((l_u16)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET] + (g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET + 1U] << 8U)) >> 4U) & 0xfffU))


#define l_u16_wr_LI0_MFS_LPressSignal2(A) \
    { \
    g_buffer_backup_data[3U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] |= (1U << 3); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    g_buffer_backup_data[3U + 1U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET + 1U]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] |= (1U << (3 + 1U)); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET + 1U] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal2_BYTE_OFFSET + 1U] & 0x00U) | \
    (((A) >> 4U) & 0xffU)); \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] &= (~(0x03 << 3)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal2_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal2_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_MFS_LPressSignal3 */
 
#define l_u16_rd_LI0_MFS_LPressSignal3() \
    ((l_u16)  (((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET] + (g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET + 1U] << 8U)) >> 0U) & 0xfffU))


#define l_u16_wr_LI0_MFS_LPressSignal3(A) \
    { \
    g_buffer_backup_data[5U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] |= (1U << 5); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    g_buffer_backup_data[5U + 1U] =  g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET + 1U]; \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] |= (1U << (5 + 1U)); \
    g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET + 1U] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_MFS_LPressSignal3_BYTE_OFFSET + 1U] & 0xf0U) | \
    (((A) >> 8U) & 0x0fU)); \
    g_lin_frame_updating_flag_tbl[LI0_MFS_LIN_1] &= (~(0x03 << 5)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal3_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal3_FLAG_BIT_OFFSET); \
    }


/* static access macros for signal LI0_MFS_LIN_1_Error */

 
#define l_bool_rd_LI0_MFS_LIN_1_Error() \
    (LIN_TEST_BIT(g_lin_frame_data_buffer[LIN_LI0_MFS_LIN_1_Error_BYTE_OFFSET], \
    LIN_LI0_MFS_LIN_1_Error_BIT_OFFSET))

#define l_bool_wr_LI0_MFS_LIN_1_Error(A) \
    {(A) ? \
    (LIN_SET_BIT(g_lin_frame_data_buffer[LIN_LI0_MFS_LIN_1_Error_BYTE_OFFSET], \
    LIN_LI0_MFS_LIN_1_Error_BIT_OFFSET)):\
    (LIN_CLEAR_BIT(g_lin_frame_data_buffer[LIN_LI0_MFS_LIN_1_Error_BYTE_OFFSET], \
    LIN_LI0_MFS_LIN_1_Error_BIT_OFFSET));\
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LIN_1_Error_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LIN_1_Error_FLAG_BIT_OFFSET);}
 
/* static access macros for signal LI0_L_BYTE1 */
 
#define l_u8_rd_LI0_L_BYTE1() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE1_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE1(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE1_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE1_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE1_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE1_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE2 */
 
#define l_u8_rd_LI0_L_BYTE2() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE2_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE2(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE2_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE2_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE2_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE2_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE3 */
 
#define l_u8_rd_LI0_L_BYTE3() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE3_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE3(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE3_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE3_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE3_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE3_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE4 */
 
#define l_u8_rd_LI0_L_BYTE4() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE4_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE4(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE4_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE4_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE4_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE4_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE5 */
 
#define l_u8_rd_LI0_L_BYTE5() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE5_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE5(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE5_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE5_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE5_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE5_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE6 */
 
#define l_u8_rd_LI0_L_BYTE6() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE6_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE6(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE6_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE6_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE6_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE6_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE7 */
 
#define l_u8_rd_LI0_L_BYTE7() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE7_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE7(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE7_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE7_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE7_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE7_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_BYTE8 */
 
#define l_u8_rd_LI0_L_BYTE8() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_BYTE8_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_BYTE8(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_BYTE8_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_BYTE8_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE8_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE8_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_Backlight */
 
#define l_u8_rd_LI0_GW_Backlight() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_Backlight_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_Backlight(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_Backlight_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_Backlight_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_Backlight_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_Backlight_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_BYTE1 */
 
#define l_u8_rd_LI0_GW_BYTE1() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE1_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_BYTE1(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_BYTE1_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE1_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE1_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE1_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_BYTE2 */
 
#define l_u8_rd_LI0_GW_BYTE2() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE2_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_BYTE2(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_BYTE2_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE2_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE2_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE2_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_BYTE3 */
 
#define l_u8_rd_LI0_GW_BYTE3() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE3_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_BYTE3(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_BYTE3_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE3_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE3_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE3_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_BYTE4 */
 
#define l_u8_rd_LI0_GW_BYTE4() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE4_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_BYTE4(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_BYTE4_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE4_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE4_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE4_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_BYTE5 */
 
#define l_u8_rd_LI0_GW_BYTE5() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE5_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_BYTE5(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_BYTE5_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE5_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE5_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE5_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_GW_BYTE6 */
 
#define l_u8_rd_LI0_GW_BYTE6() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE6_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_GW_BYTE6(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_GW_BYTE6_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_GW_BYTE6_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE6_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE6_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_Rolling */
 
#define l_u8_rd_LI0_L_Rolling() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_Rolling_BYTE_OFFSET]) >> 4U) & 0x0fU))


#define l_u8_wr_LI0_L_Rolling(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_Rolling_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_Rolling_BYTE_OFFSET] & 0x0fU) | \
    (((A) << 4U) & 0xf0U)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_Rolling_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_Rolling_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_Checksum */
 
#define l_u8_rd_LI0_L_Checksum() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_Checksum_BYTE_OFFSET]) >> 0U) & 0xffU))


#define l_u8_wr_LI0_L_Checksum(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_Checksum_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_Checksum_BYTE_OFFSET] & 0x00U) | \
    (((A) << 0U) & 0xffU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_Checksum_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_Checksum_FLAG_BIT_OFFSET); \
    }


 
/* static access macros for signal LI0_L_LB */
 
#define l_u8_rd_LI0_L_LB() \
    ((l_u8)  (((g_lin_frame_data_buffer[LIN_LI0_L_LB_BYTE_OFFSET]) >> 2U) & 0x03U))


#define l_u8_wr_LI0_L_LB(A) \
    { \
    g_lin_frame_data_buffer[LIN_LI0_L_LB_BYTE_OFFSET] = \
    (l_u8)((g_lin_frame_data_buffer[LIN_LI0_L_LB_BYTE_OFFSET] & 0xf3U) | \
    (((A) << 2U) & 0x0cU)); \
    LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_LB_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_LB_FLAG_BIT_OFFSET); \
    }




/* Signal flag APIs */

#define l_flg_tst_LI0_MFS_RPressSignal1_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal1_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal1_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_RPressSignal1_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal1_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal1_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_RPressSignal2_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal2_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal2_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_RPressSignal2_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal2_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal2_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_RPressSignal3_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal3_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal3_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_RPressSignal3_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RPressSignal3_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RPressSignal3_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_UP_switch_signal_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_UP_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_UP_switch_signal_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_UP_switch_signal_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_UP_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_UP_switch_signal_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_DOWN_switch_signal_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_DOWN_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_DOWN_switch_signal_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_DOWN_switch_signal_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_DOWN_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_DOWN_switch_signal_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_LEFT_switch_signal_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LEFT_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LEFT_switch_signal_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_LEFT_switch_signal_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LEFT_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LEFT_switch_signal_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_RIGHT_switch_signal_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_RIGHT_switch_signal_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_RIGHT_switch_signal_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_OK_switch_signal_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_OK_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_OK_switch_signal_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_OK_switch_signal_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_OK_switch_signal_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_OK_switch_signal_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_LPressSignal1_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal1_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal1_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_LPressSignal1_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal1_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal1_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_LPressSignal2_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal2_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal2_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_LPressSignal2_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal2_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal2_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_LPressSignal3_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal3_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal3_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_LPressSignal3_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LPressSignal3_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LPressSignal3_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_MFS_LIN_1_Error_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LIN_1_Error_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LIN_1_Error_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_MFS_LIN_1_Error_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_MFS_LIN_1_Error_FLAG_BYTE_OFFSET],\
         LIN_LI0_MFS_LIN_1_Error_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE1_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE1_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE1_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE1_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE1_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE1_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE2_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE2_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE2_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE2_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE2_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE2_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE3_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE3_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE3_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE3_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE3_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE3_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE4_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE4_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE4_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE4_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE4_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE4_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE5_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE5_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE5_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE5_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE5_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE5_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE6_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE6_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE6_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE6_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE6_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE6_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE7_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE7_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE7_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE7_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE7_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE7_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_BYTE8_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE8_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE8_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_BYTE8_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_BYTE8_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_BYTE8_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_Backlight_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_Backlight_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_Backlight_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_Backlight_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_Backlight_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_Backlight_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_BYTE1_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE1_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE1_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_BYTE1_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE1_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE1_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_BYTE2_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE2_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE2_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_BYTE2_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE2_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE2_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_BYTE3_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE3_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE3_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_BYTE3_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE3_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE3_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_BYTE4_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE4_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE4_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_BYTE4_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE4_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE4_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_BYTE5_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE5_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE5_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_BYTE5_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE5_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE5_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_GW_BYTE6_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE6_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE6_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_GW_BYTE6_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_GW_BYTE6_FLAG_BYTE_OFFSET],\
         LIN_LI0_GW_BYTE6_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_Rolling_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_Rolling_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_Rolling_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_Rolling_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_Rolling_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_Rolling_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_Checksum_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_Checksum_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_Checksum_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_Checksum_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_Checksum_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_Checksum_FLAG_BIT_OFFSET)

#define l_flg_tst_LI0_L_LB_flag() \
         LIN_TEST_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_LB_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_LB_FLAG_BIT_OFFSET)
#define l_flg_clr_LI0_L_LB_flag() \
         LIN_CLEAR_BIT(g_lin_flag_handle_tbl[LIN_LI0_L_LB_FLAG_BYTE_OFFSET],\
         LIN_LI0_L_LB_FLAG_BIT_OFFSET)



/* Frame flag APIs */

   /* Interface_name = LI0 */

 #define l_flg_tst_LI0_MFS_LIN_1_flag() \
          g_lin_frame_flag_handle_tbl[LI0_MFS_LIN_1]
 #define l_flg_clr_LI0_MFS_LIN_1_flag() \
          g_lin_frame_flag_handle_tbl[LI0_MFS_LIN_1] = 0

 #define l_flg_tst_LI0_TestFrame1_flag() \
          g_lin_frame_flag_handle_tbl[LI0_TestFrame1]
 #define l_flg_clr_LI0_TestFrame1_flag() \
          g_lin_frame_flag_handle_tbl[LI0_TestFrame1] = 0

 #define l_flg_tst_LI0_MFS_LIN_2_flag() \
          g_lin_frame_flag_handle_tbl[LI0_MFS_LIN_2]
 #define l_flg_clr_LI0_MFS_LIN_2_flag() \
          g_lin_frame_flag_handle_tbl[LI0_MFS_LIN_2] = 0

 #define l_flg_tst_LI0_GW_LIN_flag() \
          g_lin_frame_flag_handle_tbl[LI0_GW_LIN]
 #define l_flg_clr_LI0_GW_LIN_flag() \
          g_lin_frame_flag_handle_tbl[LI0_GW_LIN] = 0

 #define l_flg_tst_LI0_MasterReq_flag() \
          g_lin_frame_flag_handle_tbl[LI0_MasterReq]
 #define l_flg_clr_LI0_MasterReq_flag() \
          g_lin_frame_flag_handle_tbl[LI0_MasterReq] = 0

 #define l_flg_tst_LI0_SlaveResp_flag() \
          g_lin_frame_flag_handle_tbl[LI0_SlaveResp]
 #define l_flg_clr_LI0_SlaveResp_flag() \
          g_lin_frame_flag_handle_tbl[LI0_SlaveResp] = 0


/* INTERFACE MANAGEMENT */

/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_init_interface
 * Description   : This static function call to dynamic function l_ifc_init()
 *
 * Implements    : l_ifc_init_interface_Class
 *END**************************************************************************/

#define l_ifc_init_LI0() l_ifc_init(LI0)


/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_wake_up_interface
 * Description   : This static function call to dynamic function l_ifc_wake_up()
 *
 * Implements    : l_ifc_wake_up_interface_Class
 *END**************************************************************************/

#define l_ifc_wake_up_LI0() l_ifc_wake_up(LI0)


/*FUNCTION**********************************************************************
 *
 * Function Name : l_ifc_read_status_interface
 * Description   : This static function call to dynamic function l_ifc_read_status()
 *
 * Implements    : l_ifc_read_status_interface_Class
 *END**************************************************************************/

#define l_ifc_read_status_LI0() l_ifc_read_status(LI0)





#define LI0_DIAG_NUMBER_OF_SERVICES     14U

#define LI0_DIAGSRV_ASSIGN_NAD_ORDER       0U
#define LI0_DIAGSRV_READ_BY_IDENTIFIER_ORDER       1U
#define LI0_DIAGSRV_CONDITIONAL_CHANGE_NAD_ORDER       2U
#define LI0_DIAGSRV_DATA_DUMP_ORDER       3U
#define LI0_DIAGSRV_SAVE_CONFIGURATION_ORDER       4U
#define LI0_DIAGSRV_ASSIGN_FRAME_ID_RANGE_ORDER       5U
#define LI0_DIAGSRV_READ_DATA_BY_IDENTIFIER_ORDER       6U
#define LI0_DIAGSRV_WRITE_DATA_BY_IDENTIFIER_ORDER       7U
#define LI0_DIAGSRV_SESSION_CONTROL_ORDER       8U
#define LI0_DIAGSRV_IO_CONTROL_BY_IDENTIFIER_ORDER       9U
#define LI0_DIAGSRV_FAULT_MEMORY_READ_ORDER       10U
#define LI0_DIAGSRV_FAULT_MEMORY_CLEAR_ORDER       11U
#define LI0_DIAGSRV_ECU_RESET_ORDER       12U
#define LI0_DIAGSRV_SECURITY_ACCESS_ORDER       13U

#define MAX_LENGTH_SERVICE 64




#endif    /* _LIN_CFG_H_ */
